name: build
run-name: Building application(s) for multiple platforms.
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  install-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nim
        uses: alaviss/setup-nim@0.1.0
        with:
          version: 'version-2-0'
          path: 'nim'
      - name: Build
        run: |
          echo -e "y" | nimble install
          echo $(ls)
      - name: Test
        run: |
          ./passwordgen -h
          ./passwordgen -l=10
          ./passwordgen -l=10 -s
          ./passwordgen -l=10 -a
          ./passwordgen -l=10 -d
          ./passwordgen -l=10 --hash-res
          ./passwordgen -l=10 --hash-res -o=hex
          ./passwordgen -l=10 --hash-res -o=base64
          ./passwordgen -l=10 -s --hash-res
          ./passwordgen -l=10 -d --hash-res
          ./passwordgen -l=10 -a --hash-res
          ./passwordgen -l=10 -s --hash-res -o=hex
          ./passwordgen -l=10 -s --hash-res -o=base64
          ./passwordgen -l=10 -d --hash-res -o=hex
          ./passwordgen -l=10 -d --hash-res -o=base64
          ./passwordgen -l=10 -a --hash-res -o=hex
          ./passwordgen -l=10 -a --hash-res -o=base64
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            passwordgen
          generate_release_notes: true
  install-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nim
        uses: alaviss/setup-nim@0.1.0
        with:
          version: 'version-2-0'
          path: 'nim'
      - name: Build
        run: |
          "echo y | nimble build"
          echo $(ls)
      - name: Test
        run: |
          "passwordgen.exe -h"
          "passwordgen.exe -l=10"
          "passwordgen.exe -l=10 -s"
          "passwordgen.exe -l=10 -a"
          "passwordgen.exe -l=10 -d"
          "passwordgen.exe -l=10 --hash-res"
          "passwordgen.exe -l=10 --hash-res -o=hex"
          "passwordgen.exe -l=10 --hash-res -o=base64"
          "passwordgen.exe -l=10 -s --hash-res"
          "passwordgen.exe -l=10 -d --hash-res"
          "passwordgen.exe -l=10 -a --hash-res"
          "passwordgen.exe -l=10 -s --hash-res -o=hex"
          "passwordgen.exe -l=10 -s --hash-res -o=base64"
          "passwordgen.exe -l=10 -d --hash-res -o=hex"
          "passwordgen.exe -l=10 -d --hash-res -o=base64"
          "passwordgen.exe -l=10 -a --hash-res -o=hex"
          "passwordgen.exe -l=10 -a --hash-res -o=base64
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            passwordgen.exe
          generate_release_notes: true
  install-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nim
        uses: alaviss/setup-nim@0.1.0
        with:
          version: 'version-2-0'
          path: 'nim'
      - name: Build
        run: |
          echo -e "y" | nimble install
          mv passwordgen passwordgen_mac
          echo $(ls)
      - name: Test
        run: |
          ./passwordgen_mac -h
          ./passwordgen_mac -l=10
          ./passwordgen_mac -l=10 -s
          ./passwordgen_mac -l=10 -a
          ./passwordgen_mac -l=10 -d
          ./passwordgen_mac -l=10 --hash-res
          ./passwordgen_mac -l=10 --hash-res -o=hex
          ./passwordgen_mac -l=10 --hash-res -o=base64
          ./passwordgen_mac -l=10 -s --hash-res
          ./passwordgen_mac -l=10 -d --hash-res
          ./passwordgen_mac -l=10 -a --hash-res
          ./passwordgen_mac -l=10 -s --hash-res -o=hex
          ./passwordgen_mac -l=10 -s --hash-res -o=base64
          ./passwordgen_mac -l=10 -d --hash-res -o=hex
          ./passwordgen_mac -l=10 -d --hash-res -o=base64
          ./passwordgen_mac -l=10 -a --hash-res -o=hex
          ./passwordgen_mac -l=10 -a --hash-res -o=base64
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            passwordgen_mac
          generate_release_notes: true
