name: build
run-name: Building application(s) for multiple platforms.
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  install-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          export BUILD_DIR=$PWD
          curl "https://github.com/dom96/choosenim/releases/download/v0.8.4/choosenim-0.8.4_linux_amd64" -O
          mv choosenim-0.8.4_linux_amd64 choosenim
          chmod +x choosenim
          ./choosenim stable
          echo -e "y" | nimble install
          echo $(ls)
      - name: Test
        run: |
          ./passwordgen -h
          ./passwordgen -l=10
          ./passwordgen -l=10 -s
          ./passwordgen -l=10 -a
          ./passwordgen -l=10 -d
          ./passwordgen -l=10 --hash-res
          ./passwordgen -l=10 --hash-res -o=hex
          ./passwordgen -l=10 --hash-res -o=base64
          ./passwordgen -l=10 -s --hash-res
          ./passwordgen -l=10 -d --hash-res
          ./passwordgen -l=10 -a --hash-res
          ./passwordgen -l=10 -s --hash-res -o=hex
          ./passwordgen -l=10 -s --hash-res -o=base64
          ./passwordgen -l=10 -d --hash-res -o=hex
          ./passwordgen -l=10 -d --hash-res -o=base64
          ./passwordgen -l=10 -a --hash-res -o=hex
          ./passwordgen -l=10 -a --hash-res -o=base64
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            passwordgen
  install-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          SET BUILD_DIR=%CD%
          curl "https://github.com/dom96/choosenim/releases/download/v0.8.4/choosenim-0.8.4_windows_amd64.exe" -O
          mv choosenim-0.8.4_windows_amd64.exe choosenim.exe
          choosenim.exe stable
          echo -e "y" | nimble install
          echo $(ls)
      - name: Test
        run: |
          "passwordgen.exe -h"
          "passwordgen.exe -l=10"
          "passwordgen.exe -l=10 -s"
          "passwordgen.exe -l=10 -a"
          "passwordgen.exe -l=10 -d"
          "passwordgen.exe -l=10 --hash-res"
          "passwordgen.exe -l=10 --hash-res -o=hex"
          "passwordgen.exe -l=10 --hash-res -o=base64"
          "passwordgen.exe -l=10 -s --hash-res"
          "passwordgen.exe -l=10 -d --hash-res"
          "passwordgen.exe -l=10 -a --hash-res"
          "passwordgen.exe -l=10 -s --hash-res -o=hex"
          "passwordgen.exe -l=10 -s --hash-res -o=base64"
          "passwordgen.exe -l=10 -d --hash-res -o=hex"
          "passwordgen.exe -l=10 -d --hash-res -o=base64"
          "passwordgen.exe -l=10 -a --hash-res -o=hex"
          "passwordgen.exe -l=10 -a --hash-res -o=base64"
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            passwordgen.exe
  install-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          export BUILD_DIR=$PWD
          curl "https://github.com/dom96/choosenim/releases/download/v0.8.4/choosenim-0.8.4_macosx_amd64" -O
          mv choosenim-0.8.4_macosx_amd64 choosenim
          chmod +x choosenim
          ./choosenim stable
          echo -e "y" | nimble install
          echo $(ls)
      - name: Test
        run: |
          ./passwordgen -h
          ./passwordgen -l=10
          ./passwordgen -l=10 -s
          ./passwordgen -l=10 -a
          ./passwordgen -l=10 -d
          ./passwordgen -l=10 --hash-res
          ./passwordgen -l=10 --hash-res -o=hex
          ./passwordgen -l=10 --hash-res -o=base64
          ./passwordgen -l=10 -s --hash-res
          ./passwordgen -l=10 -d --hash-res
          ./passwordgen -l=10 -a --hash-res
          ./passwordgen -l=10 -s --hash-res -o=hex
          ./passwordgen -l=10 -s --hash-res -o=base64
          ./passwordgen -l=10 -d --hash-res -o=hex
          ./passwordgen -l=10 -d --hash-res -o=base64
          ./passwordgen -l=10 -a --hash-res -o=hex
          ./passwordgen -l=10 -a --hash-res -o=base64
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            passwordgen
